# GitHub Action – Black Duck Security Scan:
#     https://blackduck-dev.zoominsoftware.io/bundle/bridge/page/documentation/c_using-github-action.html
# GitHub Prerequisites:
#     https://blackduck-dev.zoominsoftware.io/bundle/bridge/page/documentation/c_github-prerequisites.html
# Additional GitHub Configuration:
#     https://blackduck-dev.zoominsoftware.io/bundle/bridge/page/documentation/c_additional-github-parameters.html
# Using the Black Duck Security Scan Action with Black Duck SCA:
#     https://blackduck-dev.zoominsoftware.io/bundle/bridge/page/documentation/c_github-blackduck.html
# Using Bridge CLI with Black Duck SCA:
#     https://blackduck-dev.zoominsoftware.io/bundle/bridge/page/documentation/c_using-bridge-with-black-duck.html
name: Black Duck Security Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}

# GitHub token permissions for post-scan actions:
# pull-requests: write - Required to add comments to pull requests
# contents: read - Required for basic workflow operations

permissions:
  contents: read
  pull-requests: write
jobs:
  blackducksca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Security Scan
        id: black-duck-security-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          blackducksca_prComment_enabled: true


          ### SCAN CONFIGURATION: Uncomment below to enable
          # blackducksca_waitForScan: true # Wait for scan completion before proceeding

          ### Mark build status if policy violating issues are found
          # mark_build_status: failure # Set to success, failure, or skip

          ### Optional configuration
          # include_diagnostics: false

          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackducksca_fixpr_enabled: false

          ### SARIF report generation and upload to GitHub Advanced Security: Uncomment below to enable
          # blackducksca_reports_sarif_create: false # Create SARIF report and upload it as artifact
          # blackducksca_upload_sarif_report: false # Upload SARIF report in GitHub Advanced Security tab

      ### Uncomment below configuration to add custom logic based on return status
      # - name: cmdLine
      #   id: cmdLine
      #   run: |
      #     EXIT_CODE=${{ steps.blackducksca-scan.outputs.status }}
      #     echo "Blackducksca Scan exit status - $EXIT_CODE"