name: Analyze External Repository

on:
  workflow_dispatch:
    inputs:
      target_repo_url:
        description: 'Target repository URL to analyze (e.g., https://github.com/microsoft/vscode)'
        required: true
        type: string
      analysis_model:
        description: 'AI model for analysis'
        default: 'claude-sonnet'
        type: choice
        options:
          - claude-sonnet
          - gpt-4
          - gemini
      analysis_depth:
        description: 'Depth of analysis to perform'
        default: 'standard'
        type: choice
        options:
          - quick
          - standard
          - deep
      custom_config:
        description: 'Custom configuration file path (optional)'
        required: false
        type: string

jobs:
  analyze-repository:
    name: Analyze ${{ inputs.target_repo_url }}
    uses: bd-SrinathAkkem/repo-analyzer/.github/workflows/analyze_repo.yml@main
    with:
      repo_url: ${{ inputs.target_repo_url }}
      model: ${{ inputs.analysis_model }}
      config_file: ${{ inputs.custom_config }}
      analysis_depth: ${{ inputs.analysis_depth }}
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
