name: Polaris Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  analyze-repository:
    runs-on: self-hosted
    steps:
      - name: Analyze ${{ github.repository }}
        uses: bd-SrinathAkkem/repo-analyzer/.github/workflows/analyze_repo.yml@main
        with:
          repo_url: https://github.com/${{ github.repository }}
          model: claude-sonnet
  polaris:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Polaris Security Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: SAST,SCA
          polaris_waitForScan: true
          mark_build_status: failure
          include_diagnostics: true
          polaris_prComment_enabled: false
          polaris_reports_sarif_create: false
          polaris_upload_sarif_report: false
